spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/test?useUnicode=true&amp;characterEncoding=utf-8  
    username: root
    password: 123456
  application:
    name: workflow-service  
  activiti:
    history-level: full
server:
  port: 8081
  servlet:
    context-path: /workflow 
    
#debug: true
logging:
  file: workflow.log
  level:
    root: warn
    com.misrobot: debug
    org.activiti.engine.impl.persistence.entity: debug
    org.activiti.engine.impl.interceptor: debug
    org.activiti.engine.impl.db.DbSqlSession: debug
#    org.springframework: debug
#    springfox: debug
    org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider: trace

eureka:
  instance:
    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health
  client: 
    serviceUrl:
#      defaultZone: ${{EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE}:http://eureka-server:1025/eureka/}
      defaultZone: ${{EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE}:http://192.168.0.101:1025/eureka/}
